{
 "title": "online-shop-app",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "15s,1m,2m,3m,5m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[MOL] Current RPS",
   "type": "stat",
   "description": "Среднее количество запросов в секунду за последние N секунд, где N - указанный интервал",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_total{type=\"remote\"}[${interval}]))"
    }
   ]
  },
  {
   "title": "[MOL] RPS",
   "type": "timeseries",
   "description": "Количество запросов в секунду",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_total{type=\"remote\"}[${interval}]))"
    }
   ]
  },
  {
   "title": "[MOL] RPS grouped by actions",
   "type": "timeseries",
   "description": "Количество запросов в секунду с группировкой по action'ам (endpoint'ам)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(action)(rate(moleculer_request_total{type=\"remote\"}[${interval}]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "[MOL] Error rate (%)",
   "type": "timeseries",
   "description": "Процент 500'х ошибок относительно общего количества запросов",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_error_total{type=\"remote\"}[${interval}])) / sum(rate(moleculer_request_total{type=\"remote\"}[${interval}])) * 100",
     "legendFormat": "moleculer error rate"
    }
   ]
  },
  {
   "title": "[MOL] Current error rate (%)",
   "type": "stat",
   "description": "Средний процент 500'х ошибок относительно общего количества запросов за последние N секунд, где N - указанный интервал",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_error_total{type=\"remote\"}[${interval}])) / sum(rate(moleculer_request_total{type=\"remote\"}[${interval}])) * 100",
     "legendFormat": "moleculer error rate"
    }
   ]
  },
  {
   "title": "[MOL] Error rate grouped by actions (%)",
   "type": "timeseries",
   "description": "Процент 500'х ошибок относительно общего количества запросов, сгруппированных по action'ам (endpoint'ам)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(moleculer_request_error_total{type=\"remote\"}[${interval}])) / sum by (action) (rate(moleculer_request_total{type=\"remote\"}[${interval}])) * 100",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "[MOL] Latency (ms)",
   "type": "timeseries",
   "description": "Среднее время выполнения запросов в миллисекундах",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_time_sum{type=\"remote\"}[${interval}])) / sum(rate(moleculer_request_time_count{type=\"remote\"}[${interval}]))"
    }
   ]
  },
  {
   "title": "[MOL] Current latency (ms)",
   "type": "stat",
   "description": "Среднее время выполнения запросов в миллисекундах за последние N секунд, где N - указанный интервал",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_time_sum{type=\"remote\"}[${interval}])) / sum(rate(moleculer_request_time_count{type=\"remote\"}[${interval}]))"
    }
   ]
  },
  {
   "title": "[MOL] Percentiles of latencies requests (manual)",
   "type": "timeseries",
   "description": "Процентили задержек запросов (посчитано вручную)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(moleculer_request_time_bucket{type=\"remote\"}[${interval}])) by (le))",
     "legendFormat": "50%-tile latency of requests"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(moleculer_request_time_bucket{type=\"remote\"}[${interval}])) by (le))",
     "legendFormat": "95%-tile latency of requests"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(moleculer_request_time_bucket{type=\"remote\"}[${interval}])) by (le))",
     "legendFormat": "99%-tile latency of requests"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(moleculer_request_time_bucket{type=\"remote\"}[${interval}])) by (le))",
     "legendFormat": "99.9%-tile latency of requests"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } }
 ]
}